title:         "Bold&Adventurous"
tagline:       "Bold & Adventurous"
description:   "Tiny house, big backyard! We're a family of 4 traveling the USA in our Airstream."
email:         "mike@mk3y.com"
baseurl:     
url:           https://boldandadventurous.com

markdown:	   kramdown

paginate:      3
paginate_path: /blog/:num/

permalink:     /:title/

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
    - README.md
    - CNAME
    - Gemfile

sass:
    sass_dir: "assets/_sass/"
    style: compressed