#Dev Mode?
development: false

#Getting Started
title:          "Bold&Adventurous"
tagline:        "Bold & Adventurous"
description:    "Tiny house, big backyard! We're a family of 4 traveling the USA in our Airstream."
email:          "mike@mk3y.com"

# Site Config
baseurl:     ""
url:         "https://boldandadventurous.com"

# Dependencies
markdown:	kramdown

# Permalinks
permalink:	pretty

#Display Settings
paginate:	5
paginate_path: "page:num"

# Custom vars
icon:       "/assets/img/icon.png"
cover:      "https://lh3.googleusercontent.com/kKsizieETQ0J1rc5YSIB-lEs1msXf8dAj70JtqSqVFA=w1232-h790-no"

# Extra Gems
gems:
  - jekyll-sitemap

# Build settings
timezone: America/New York
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Assets Pipeline
sass:
 sass_dir: "assets/css/"
 style: :compressed